const express = require("express");
const http = require("http");
const app = express();
const { Server } = require("socket.io");
const cors = require("cors");

app.use(cors());
const server = http.createServer(app);

const io = new Server(server, {
  cors: {
    origin: [
      "http://localhost",
      "http://192.168.1.39",
      "http://192.168.1.59",
      "http://192.168.1.44",
      "http://192.168.190.118",
      "http://192.168.1.43:5173",
      "http://192.168.0.213:5173"
    ],
    methods: ["GET", "POST"],
  },
});

const PORT = process.env.PORT || 3001;
// let words = ["ability", "able", "about", "above", "accept", "according", "account", "across", "act", "action", "activity", "actually", "add", "address", "administration", "admit", "adult", "affect", "after", "again", "against", "age", "agency", "agent", "ago", "agree", "agreement", "ahead", "air", "all", "allow", "almost", "alone", "along", "already", "also", "although", "always", "American", "among", "amount", "analysis", "and", "animal", "another", "answer", "any", "anyone", "anything", "appear", "apply", "approach", "area", "argue", "arm", "around", "arrive", "art", "article", "artist", "as", "ask", "assume", "at", "attack", "attention", "attorney", "audience", "author", "authority", "available", "avoid", "away", "baby", "back", "bad", "bag", "ball", "bank", "bar", "base", "be", "beat", "beautiful", "because", "become", "bed", "before", "begin", "behavior", "behind", "believe", "benefit", "best", "better", "between", "beyond", "big", "bill", "billion", "bit", "black", "blood", "blue", "board", "body", "book", "born", "both", "box", "boy", "bring", "brother", "budget", "build", "building", "business", "but", "buy", "by", "call", "camera", "campaign", "can", "cancer", "candidate", "capital", "car", "card", "care", "career", "carry", "cause", "cell", "center", "central", "century", "certain", "certainly", "chair", "challenge", "chance", "change", "character", "charge", "check", "child", "choice", "choose", "church", "citizen", "city", "civil", "claim", "clear", "clearly", "close", "coach", "cold", "collection", "college", "color", "come", "commercial", "common", "community", "company", "compare", "computer", "concern", "condition", "conference", "Congress", "consider", "consumer", "contain", "control", "cost", "could", "country", "couple", "course", "court", "cover", "create", "crime", "cultural", "culture", "cup", "current", "customer", "cut", "dark", "data", "daughter", "day", "dead", "deal", "death", "debate", "decade", "decide", "decision", "deep", "defense", "degree", "Democrat", "democratic", "describe", "design", "despite", "detail", "determine", "develop", "development", "die", "difference", "different", "difficult", "dinner", "direction", "director", "discover", "discuss", "discussion", "disease", "doctor", "dog", "door", "down", "draw", "dream", "drive", "drop", "drug", "during", "each", "early", "east", "easy", "eat", "economic", "economy", "edge", "education", "effect", "effort", "eight", "either", "election", "employee", "end", "energy", "enjoy", "enough", "enter", "entire", "environment", "environmental", "especially", "establish", "even", "evening", "event", "ever", "every", "everybody", "everyone", "everything", "evidence", "exactly", "example", "executive", "exist", "expect", "experience", "expert", "explain", "eye", "face", "fact", "factor", "fail", "fall", "family", "far", "fast", "father", "fear", "federal", "feel", "feeling", "few", "field", "fight", "figure", "fill", "film", "financial", "find", "fine", "finger", "finish", "fire", "firm", "first", "fish", "five", "floor", "fly", "focus", "follow", "food", "foot", "force", "foreign", "forget", "form", "former", "forward", "four", "free", "friend", "from", "front", "full", "fund", "future", "game", "garden", "gas", "general", "generation", "get", "girl", "give", "glass", "go", "goal", "good", "government", "great", "green", "ground", "group", "grow", "growth", "guess", "gun", "guy", "hair", "half", "hand", "hang", "happen", "happy", "hard", "have", "he", "head", "health", "hear", "heart", "heat", "heavy", "help", "her", "here", "herself", "high", "him", "himself", "his", "history", "hit", "hold", "home", "hope", "hospital", "hot", "hotel", "hour", "house", "how", "however", "huge", "human", "hundred", "husband", "I", "idea", "identify", "image", "imagine", "impact", "important", "improve", "in", "include", "including", "increase", "indeed", "indicate", "individual", "industry", "information", "inside", "instead", "institution", "interest", "interesting", "international", "interview", "into", "investment", "involve", "issue", "it", "item", "its", "itself", "job", "join", "just", "keep", "key", "kid", "kill", "kind", "kitchen", "know", "knowledge", "land", "language", "large", "last", "late", "later", "laugh", "law", "lawyer", "lay", "lead", "leader", "learn", "least", "leave", "left", "leg", "legal", "less", "let", "letter", "level", "lie", "life", "light", "like", "likely", "line", "list", "listen", "little", "live", "local", "look", "lose", "loss", "lot", "love", "low", "machine", "magazine", "main", "maintain", "major", "majority", "make", "man", "manage", "management", "manager", "many", "market", "marriage", "material", "matter", "may", "maybe", "me", "mean", "measure", "media", "medical", "meet", "meeting", "member", "memory", "mention", "message", "method", "middle", "might", "military", "million", "mind", "minute", "miss", "mission", "model", "modern", "moment", "money", "month", "more", "morning", "most", "mother", "mouth", "move", "movement", "movie", "Mr", "Mrs", "much", "music", "must", "my", "myself", "name", "nation", "national", "natural", "nature", "near", "nearly", "necessary", "need", "network", "never", "news", "newspaper", "next", "nice", "night", "no", "none", "nor", "north", "not", "note", "nothing", "notice", "now", "number", "occur", "of", "off", "offer", "office", "officer", "official", "often", "oh", "oil", "ok", "old", "on", "once", "one", "only", "onto", "open", "operation", "opportunity", "option", "or", "order", "organization", "other", "others", "our", "out", "outside", "over", "own", "owner", "page", "pain", "painting", "paper", "parent", "part", "participant", "particular", "particularly", "partner", "party", "pass", "past", "patient", "pattern", "pay", "peace", "people", "per", "perform", "performance", "perhaps", "period", "person", "personal", "phone", "physical", "pick", "picture", "piece", "place", "plan", "plant", "play", "player", "PM", "point", "police", "policy", "political", "politics", "poor", "popular", "population", "position", "positive", "possible", "power", "practice", "prepare", "present", "president", "pressure", "pretty", "prevent", "price", "probably", "problem", "process", "produce", "product", "production", "professional", "professor", "program", "project", "property", "protect", "prove", "provide", "pull", "purpose", "push", "put", "quality", "question", "quickly", "quite", "race", "radio", "raise", "range", "rate", "rather", "reach", "read", "ready", "real", "reality", "realize", "really", "reason", "receive", "recent", "recently", "recognize", "record", "red", "reduce", "reflect", "region", "relate", "relationship", "religious", "remain", "remember", "remove", "report", "represent", "Republican", "require", "research", "resource", "respond", "response", "responsibility", "rest", "result", "reveal", "rich", "right", "rise", "risk", "road", "rock", "role", "room", "rule", "run", "safe", "same", "save", "say", "scene", "school", "science", "scientist", "score", "sea", "season", "seat", "second", "section", "security", "see", "seek", "seem", "sell", "send", "senior", "sense", "series", "serious", "serve", "service", "set", "seven", "several", "sex", "sexual", "shake", "share", "she", "shoot", "shot", "should", "shoulder", "show", "side", "sign", "significant", "similar", "simple", "simply", "since", "sing", "single", "sister", "sit", "site", "situation", "six", "size", "skill", "skin", "small", "smile", "so", "social", "society", "soldier", "some", "somebody", "someone", "something", "sometimes", "son", "song", "soon", "sort", "sound", "source", "south", "southern", "space", "speak", "special", "specific", "speech", "spend", "sport", "spring", "staff", "stage", "stand", "standard", "star", "start", "state", "statement", "station", "stay", "step", "still", "stock", "stop", "store", "story", "strategy", "street", "strong", "structure", "student", "study", "stuff", "style", "subject", "success", "successful", "such", "suddenly", "suffer", "suggest", "summer", "support", "sure", "surface", "system", "table", "take", "talk", "task", "tax", "teach", "teacher", "team", "technology", "television", "tell", "ten", "tend", "term", "test", "than", "thank", "that", "the", "their", "them", "themselves", "then", "theory", "there", "these", "they", "thing", "think", "third", "those", "though", "thought", "thousand", "threat", "three", "through", "throughout", "thus", "time", "to", "today", "together", "tonight", "too", "top", "total", "tough", "toward", "town", "trade", "traditional", "training", "travel", "treat", "treatment", "tree", "trial", "trip", "trouble", "true", "truth", "turn", "TV", "two", "type", "under", "understand", "unit", "until", "up", "upon", "us", "use", "usually", "value", "various", "very", "victim", "view", "violence", "visit", "voice", "vote", "wait", "walk", "wall", "want", "war", "watch", "water", "way", "we", "weapon", "wear", "week", "weight", "well", "west", "western", "what", "whatever", "when", "where", "whether", "which", "white", "who", "whole", "whom", "whose", "why", "wide", "wife", "will", "win", "wind", "window", "wish", "with", "within", "without", "woman", "wonder", "word", "work", "worker", "world", "worry", "would", "write", "writer", "wrong", "yard", "yeah", "year", "yes", "yet", "you", "young", "your", "yourself"];
let words = [
  "able",
  "about",
  "above",
  "accept",
  "across",
  "act",
  "action",
  "add",
  "admit",
  "adult",
  "affect",
  "after",
  "again",
  "age",
  "agency",
  "agent",
  "ago",
  "agree",
  "ahead",
  "air",
  "all",
  "allow",
  "almost",
  "alone",
  "along",
  "also",
  "always",
  "among",
  "amount",
  "and",
  "animal",
  "answer",
  "any",
  "anyone",
  "appear",
  "apply",
  "area",
  "argue",
  "arm",
  "around",
  "arrive",
  "art",
  "artist",
  "as",
  "ask",
  "assume",
  "at",
  "attack",
  "author",
  "avoid",
  "away",
  "baby",
  "back",
  "bad",
  "bag",
  "ball",
  "bank",
  "bar",
  "base",
  "be",
  "beat",
  "become",
  "bed",
  "before",
  "begin",
  "behind",
  "best",
  "better",
  "beyond",
  "big",
  "bill",
  "bit",
  "black",
  "blood",
  "blue",
  "board",
  "body",
  "book",
  "born",
  "both",
  "box",
  "boy",
  "bring",
  "budget",
  "build",
  "but",
  "buy",
  "by",
  "call",
  "camera",
  "can",
  "cancer",
  "car",
  "card",
  "care",
  "career",
  "carry",
  "cause",
  "cell",
  "center",
  "chair",
  "chance",
  "change",
  "charge",
  "check",
  "child",
  "choice",
  "choose",
  "church",
  "city",
  "civil",
  "claim",
  "clear",
  "close",
  "coach",
  "cold",
  "color",
  "come",
  "common",
  "cost",
  "could",
  "couple",
  "course",
  "court",
  "cover",
  "create",
  "crime",
  "cup",
  "cut",
  "dark",
  "data",
  "day",
  "dead",
  "deal",
  "death",
  "debate",
  "decade",
  "decide",
  "deep",
  "degree",
  "design",
  "detail",
  "die",
  "dinner",
  "doctor",
  "dog",
  "door",
  "down",
  "draw",
  "dream",
  "drive",
  "drop",
  "drug",
  "during",
  "each",
  "early",
  "east",
  "easy",
  "eat",
  "edge",
  "effect",
  "effort",
  "eight",
  "either",
  "end",
  "energy",
  "enjoy",
  "enough",
  "enter",
  "entire",
  "even",
  "event",
  "ever",
  "every",
  "exist",
  "expect",
  "expert",
  "eye",
  "face",
  "fact",
  "factor",
  "fail",
  "fall",
  "family",
  "far",
  "fast",
  "father",
  "fear",
  "feel",
  "few",
  "field",
  "fight",
  "figure",
  "fill",
  "film",
  "find",
  "fine",
  "finger",
  "finish",
  "fire",
  "firm",
  "first",
  "fish",
  "five",
  "floor",
  "fly",
  "focus",
  "follow",
  "food",
  "foot",
  "force",
  "forget",
  "form",
  "former",
  "four",
  "free",
  "friend",
  "from",
  "front",
  "full",
  "fund",
  "future",
  "game",
  "garden",
  "gas",
  "get",
  "girl",
  "give",
  "glass",
  "go",
  "goal",
  "good",
  "great",
  "green",
  "ground",
  "group",
  "grow",
  "growth",
  "guess",
  "gun",
  "guy",
  "hair",
  "half",
  "hand",
  "hang",
  "happen",
  "happy",
  "hard",
  "have",
  "he",
  "head",
  "health",
  "hear",
  "heart",
  "heat",
  "heavy",
  "help",
  "her",
  "here",
  "high",
  "him",
  "his",
  "hit",
  "hold",
  "home",
  "hope",
  "hot",
  "hotel",
  "hour",
  "house",
  "how",
  "huge",
  "human",
  "I",
  "idea",
  "image",
  "impact",
  "in",
  "indeed",
  "inside",
  "into",
  "issue",
  "it",
  "item",
  "its",
  "itself",
  "job",
  "join",
  "just",
  "keep",
  "key",
  "kid",
  "kill",
  "kind",
  "know",
  "land",
  "large",
  "last",
  "late",
  "later",
  "laugh",
  "law",
  "lawyer",
  "lay",
  "lead",
  "leader",
  "learn",
  "least",
  "leave",
  "left",
  "leg",
  "legal",
  "less",
  "let",
  "letter",
  "level",
  "lie",
  "life",
  "light",
  "like",
  "likely",
  "line",
  "list",
  "listen",
  "little",
  "live",
  "local",
  "look",
  "lose",
  "loss",
  "lot",
  "love",
  "low",
  "main",
  "major",
  "make",
  "man",
  "manage",
  "many",
  "market",
  "matter",
  "may",
  "maybe",
  "me",
  "mean",
  "media",
  "meet",
  "member",
  "memory",
  "method",
  "middle",
  "might",
  "mind",
  "minute",
  "miss",
  "model",
  "modern",
  "moment",
  "money",
  "month",
  "more",
  "most",
  "mother",
  "mouth",
  "move",
  "movie",
  "Mr",
  "Mrs",
  "much",
  "music",
  "must",
  "my",
  "myself",
  "name",
  "nation",
  "nature",
  "near",
  "nearly",
  "need",
  "never",
  "news",
  "next",
  "nice",
  "night",
  "no",
  "none",
  "nor",
  "north",
  "not",
  "note",
  "notice",
  "now",
  "number",
  "occur",
  "of",
  "off",
  "offer",
  "office",
  "often",
  "oh",
  "oil",
  "ok",
  "old",
  "on",
  "once",
  "one",
  "only",
  "onto",
  "open",
  "option",
  "or",
  "order",
  "other",
  "others",
  "our",
  "out",
  "over",
  "own",
  "owner",
  "page",
  "pain",
  "paper",
  "parent",
  "part",
  "party",
  "pass",
  "past",
  "pay",
  "peace",
  "people",
  "per",
  "period",
  "person",
  "phone",
  "pick",
  "piece",
  "place",
  "plan",
  "plant",
  "play",
  "player",
  "PM",
  "point",
  "police",
  "policy",
  "poor",
  "power",
  "pretty",
  "price",
  "prove",
  "pull",
  "push",
  "put",
  "quite",
  "race",
  "radio",
  "raise",
  "range",
  "rate",
  "rather",
  "reach",
  "read",
  "ready",
  "real",
  "really",
  "reason",
  "recent",
  "record",
  "red",
  "reduce",
  "region",
  "relate",
  "remain",
  "remove",
  "report",
  "rest",
  "result",
  "reveal",
  "rich",
  "right",
  "rise",
  "risk",
  "road",
  "rock",
  "role",
  "room",
  "rule",
  "run",
  "safe",
  "same",
  "save",
  "say",
  "scene",
  "school",
  "score",
  "sea",
  "season",
  "seat",
  "second",
  "see",
  "seek",
  "seem",
  "sell",
  "send",
  "senior",
  "sense",
  "series",
  "serve",
  "set",
  "seven",
  "sex",
  "sexual",
  "shake",
  "share",
  "she",
  "shoot",
  "shot",
  "should",
  "show",
  "side",
  "sign",
  "simple",
  "simply",
  "since",
  "sing",
  "single",
  "sister",
  "sit",
  "site",
  "six",
  "size",
  "skill",
  "skin",
  "small",
  "smile",
  "so",
  "social",
  "some",
  "son",
  "song",
  "soon",
  "sort",
  "sound",
  "source",
  "south",
  "space",
  "speak",
  "speech",
  "spend",
  "sport",
  "spring",
  "staff",
  "stage",
  "stand",
  "star",
  "start",
  "state",
  "stay",
  "step",
  "still",
  "stock",
  "stop",
  "store",
  "story",
  "street",
  "strong",
  "study",
  "stuff",
  "style",
  "such",
  "suffer",
  "summer",
  "sure",
  "system",
  "table",
  "take",
  "talk",
  "task",
  "tax",
  "teach",
  "team",
  "tell",
  "ten",
  "tend",
  "term",
  "test",
  "than",
  "thank",
  "that",
  "the",
  "their",
  "them",
  "then",
  "theory",
  "there",
  "these",
  "they",
  "thing",
  "think",
  "third",
  "those",
  "though",
  "threat",
  "three",
  "thus",
  "time",
  "to",
  "today",
  "too",
  "top",
  "total",
  "tough",
  "toward",
  "town",
  "trade",
  "travel",
  "treat",
  "tree",
  "trial",
  "trip",
  "true",
  "truth",
  "turn",
  "TV",
  "two",
  "type",
  "under",
  "unit",
  "until",
  "up",
  "upon",
  "us",
  "use",
  "value",
  "very",
  "victim",
  "view",
  "visit",
  "voice",
  "vote",
  "wait",
  "walk",
  "wall",
  "want",
  "war",
  "watch",
  "water",
  "way",
  "we",
  "weapon",
  "wear",
  "week",
  "weight",
  "well",
  "west",
  "what",
  "when",
  "where",
  "which",
  "white",
  "who",
  "whole",
  "whom",
  "whose",
  "why",
  "wide",
  "wife",
  "will",
  "win",
  "wind",
  "window",
  "wish",
  "with",
  "within",
  "woman",
  "wonder",
  "word",
  "work",
  "worker",
  "world",
  "worry",
  "would",
  "write",
  "writer",
  "wrong",
  "yard",
  "yeah",
  "year",
  "yes",
  "yet",
  "you",
  "young",
  "your",
];
let data = [
  {
    id: "1",
    score: 0,
    question: words[Math.floor(Math.random() * (words.length - 0) + 0)],
    textInput: "",
    isIncorrect: false,
    disabledInput: false,
  },
  {
    id: "2",
    score: 0,
    question: words[Math.floor(Math.random() * (words.length - 0) + 0)],
    textInput: "",
    isIncorrect: false,
    disabledInput: false,
  },
  {
    id: "3",
    score: 0,
    question: words[Math.floor(Math.random() * (words.length - 0) + 0)],
    textInput: "",
    isIncorrect: false,
    disabledInput: false,
  },
  {
    id: "4",
    score: 0,
    question: words[Math.floor(Math.random() * (words.length - 0) + 0)],
    textInput: "",
    isIncorrect: false,
    disabledInput: false,
  },
];

let time = 0;

app.get("/", (req, res) => {
  res.send("Backend Something Game");
});

io.on("connection", (socket) => {
  console.log("connected");

  // Send the initial data to the client
  socket.emit("initial-data", data);

  socket.emit("time", time);

  socket.on("time", (updateTime) => {
    time = updateTime;
    io.emit("time", time);
  });

  socket.on("update-score", (id, newScore) => {
    const player = data.findIndex((player) => player.id === id);
    if (player !== -1) {
      data[player] = {
        ...data[player],
        score: newScore,
      };
      io.emit("updated-data", data);
    }
  });

  socket.on("update-question", (id, newQuestion) => {
    const player = data.findIndex((player) => player.id === id);
    if (player !== -1) {
      data[player] = {
        ...data[player],
        question: newQuestion,
      };
      io.emit("updated-data", data);
    }
  });

  socket.on("update-textInput", (id, NewTextInput) => {
    const player = data.findIndex((player) => player.id === id);
    if (player !== -1) {
      data[player] = {
        ...data[player],
        textInput: NewTextInput,
      };
      io.emit("updated-data", data);
    }
  });

  socket.on("update-isIncorrect", (id, NewisIncorrect) => {
    const player = data.findIndex((player) => player.id === id);
    if (player !== -1) {
      data[player] = {
        ...data[player],
        isIncorrect: NewisIncorrect,
      };
      io.emit("updated-data", data);
    }
  });

  socket.on("update-disabledInput", (id, NewDisabledInput) => {
    const player = data.findIndex((player) => player.id === id);
    if (player !== -1) {
      data[player] = {
        ...data[player],
        disabledInput: NewDisabledInput,
      };
      io.emit("updated-data", data);
    }
  });

  socket.on("message", (message) => {
    io.emit("message", message);
  });

  socket.on("disconnect", () => {
    console.log("disconnected");
  });
});

server.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
